version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql_service
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: football_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    
volumes:
  mysql_data:
    driver: local